export const data = [
    { id: 1, name: "Ajaya Kumar Das", image: "https://images.geekster.in/placed/Ajaya-Kumar-Das.webp", description: "I was hoping to get a job after completing the whole course. But luckily I didn't have to wait for six months, as I got a job just after four months. I'm excited to take further mentoring from Geekster.", company: "https://images.geekster.in/hiring-partners/genpact.webp" },
    { id: 2, name: "Amanpreet Singh", image: "https://images.geekster.in/placed/Amanpreet-Singh.webp", description: "Just after a year of experience, when my counterparts are still getting hold of the industry, Geekster had already skyrocketed my career! Thank you wonderful mentors and trainees at Geekster for honing my skills and instilling so much confidence in me.", company: "https://images.geekster.in/hiring-partners/PayPal.webp" },
    { id: 3, name: "Anurag Ojha", image: "https://images.geekster.in/placed/Anurag-Ojha.webp", description: "I was struggling in my initial days, because I wasn't getting a decent salary. To be honest, when I heard of Geekster's ISA program, I thought there must be some hidden charges. But I still wanted to take a chance and to my surprise, I had to pay the fees only after I got my job and that too in installments. And finally I have a job that I wished for.", company: "https://images.geekster.in/hiring-partners/skillgigs.webp"},
    { id: 4, name: "Ashwini Kumar", image: "https://images.geekster.in/placed/Ashwini-Kumar.webp", description: "I am currently going through the full-stack development program at Geekster and I couldn’t be happier with the pace of learning and support provided by my mentors. We are learning live coding with the help of Aman Sir’s constant encouragement and guidance.", company: "https://images.geekster.in/hiring-partners/ivy.webp"},
    { id: 5, name: "Bhavesh Gupta", image: "https://images.geekster.in/placed/Bhavesh-Gupta.webp", description: "The undue pressure of landing a job after college was frustrating, and the underpaid interships only made me feel underappreciated. But then I stumbled upon Geeskter which not only helped me upskill but also made me interview ready. I am glad I choose Geekster, and would recommend it to my other friends too.", company: "https://images.geekster.in/hiring-partners/shiprocket.webp"},
    { id: 6, name: "Chandani Patel", image: "https://images.geekster.in/hero-section/WebOnFocus4.png", description: "Through Geekster I improved my both areas technical as well as soft skill. Tutors always make class really interactive so we can enjoy our learning process and also so many times they have arranged doubt sessions. Personally it was such a memorable learning period. Thanks a lot!!!!", company: "https://images.geekster.in/hiring-partners/Crimson_AI_logo.webp"},
    { id: 7, name: "Chetan", image: "https://images.geekster.in/placed/Chetan.webp", description: "Expert tutors, excellent courses, and a guranteed job.. That's Geekster for you! Will highly recommend it to all my friends looking for a job or a switch.", company: "https://images.geekster.in/hiring-partners/societe-generale.webp"},
    { id: 8, name: "Dnyaneshwar Ghodse", image: "https://images.geekster.in/placed/Dnyaneshwar-Ghodse.webp", description: "Having completed my graduation in 2016, I thought I could never become a decent programmer. But Geekster proved me wrong and helped me land a job as a Frontend developer. Thank you Geekster!”", company: "https://images.geekster.in/hiring-partners/dhwani-RIS.webp"},
    { id: 9, name: "Gajendra Malviya", image: "https://images.geekster.in/placed/Gajendra-Malviya.webp", description: "From '0 offers' to 'multiple offers, that has been my journey at Geekster. My happiness multiplies when I see my proud family. It is the learnings and guidance I received during the course that had brought me success.", company: "https://images.geekster.in/hiring-partners/riskcovry.webp"},
    { id: 10, name: "Gopinath", image: "https://images.geekster.in/placed/Gopinath.webp", description: "I joined Geekster because they were giving guranteed placement at good companies. But I must say, it's not just a job I have got, but a lot of knowledge, enhanced technical and soft-skills, and a life-long attitude of growth and winning. Thank you so much Geekster!", company: "https://images.geekster.in/hiring-partners/societe-generale.webp"}
]